# Generated by Django 5.2.3 on 2025-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0005_alter_transaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(default='UPI', max_length=20),
        ),
    ]
