# Generated by Django 5.2.3 on 2025-08-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0010_beneficiary_beneficiary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='ifsc_code',
            new_name='ifsc',
        ),
    ]
