# Generated by Django 5.2.3 on 2025-08-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0011_rename_ifsc_code_beneficiary_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('debit', 'Debited'), ('credit', 'Credited')], default='debit', max_length=10),
        ),
    ]
