# Generated by Django 5.2.3 on 2025-08-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0012_transaction_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('deposit', 'Deposit')], default='debit', max_length=10),
        ),
    ]
