# Generated by Django 5.2.3 on 2025-08-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0013_alter_transaction_tx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tpin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upi_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
