# Generated by Django 5.2.3 on 2025-08-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0014_userprofile_tpin_userprofile_upi_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_upi', models.CharField(blank=True, max_length=100)),
                ('receiver_account', models.CharField(blank=True, max_length=20)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('NEFT', 'NEFT'), ('IMPS', 'IMPS')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tpin', models.CharField(max_length=10)),
                ('schedule_datetime', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
