# Generated by Django 5.2.3 on 2025-08-10 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0016_upirequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Gas', 'Gas')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('Deposit', 'Deposit'), ('Bill Payment', 'Bill Payment')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
