# Generated by Django 5.2.3 on 2025-08-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0017_transaction_bill_type_alter_transaction_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscriber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
