# Generated by Django 5.2.3 on 2025-08-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0018_transaction_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operator',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Gas', 'Gas'), ('Mobile', 'Mobile Recharge'), ('DTH', 'DTH Recharge')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('Deposit', 'Deposit'), ('Bill Payment', 'Bill Payment'), ('Recharge', 'Recharge')], default='UPI', max_length=20),
        ),
    ]
