# Generated by Django 5.2.3 on 2025-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank1', '0022_savednumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(choices=[('FASTAG', 'FASTag Top-up'), ('METRO', 'Metro Card Top-up')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vehicle_or_card_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upi_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
