from django.urls import path
from . import views



urlpatterns = [
    path('home/',views.home, name = 'home'),
    path('create/', views.create, name='create'),
    path('main/<int:pk>',views.main,name ='main'),
    path('logout/', views.logout_view, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/<int:pk>',views.user_update, name='update'),
    path('deletes/<int:pk>/',views.deletes, name = 'deletes'),
    # path('list',views.list,name='list'),
    path('login/', views.user_login, name='login'),
    path('upi/',views.upi,name= 'upi'),
    path('set-upi/', views.set_upi, name='set_upi'),
    path('edit_upi_pin/', views.edit_upi_pin, name='edit_upi_pin'),
    path('transfer/', views.transfer_money, name='transfer'),
    path('deposit/',views.deposit_by_account, name = 'deposit'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('register-user/', views.register, name='register'),
    path("pending-users/", views.pending_users, name="pending_users"),
    path("approve-user/<int:pk>/", views.approve_user, name="approve_user"),
    path('notifications',views.notifications, name = 'notifications'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('get_upi_name/',views.get_upi_name, name='get_upi_name'),
    path('update_pending_neft_transactions/', views.update_pending_neft_transactions, name='update_pending_neft_transactions'),
    path('bank_transfer', views.bank_transfer, name='bank_transfer'),
    path('set_tpin/', views.set_tpin, name='set_tpin'),
     path('edit-tpin/', views.edit_tpin, name='edit_tpin'),
    path('get_account_name/', views.get_account_name, name='get_account_name'),
    path('statement/', views.account_statement, name='statement'),
    path('statement/download/', views.download_statement, name='download_statement'),
    path('beneficiaries/', views.beneficiary_dashboard, name='beneficiary_dashboard'),
    # path('beneficiaries/delete/<int:pk>/', views.delete_beneficiary, name='delete_beneficiary'),
    path('edit/<int:pk>/', views.edit_beneficiary, name='edit_beneficiary'),
    path('beneficiaries/<int:pk>/pay/', views.pay_beneficiary, name='pay_beneficiary'),
    path('schedule_transfer/', views.schedule_transfer, name='schedule_transfer'),
    path('get_beneficiary_name/', views.get_beneficiary_name, name='get_beneficiary_name'),
    path('request-money/', views.request_money_upi, name='request_money_upi'),
    path('upi/requests/', views.upi_requests_received, name='upi_requests_received'),
    path('upi/handle/<int:request_id>/<str:action>/', views.handle_upi_request, name='handle_upi_request'),
    path("verify-biller/", views.verify_biller, name="verify_biller"),
    path("demo-payment/", views.demo_payment, name="demo_payment"),
    path('recharge_demo', views.recharge_demo, name='recharge_demo'),
    # path('recharge/success/<int:tx_id>/', views.recharge_success, name='recharge_success'),
    path("fastag_home", views.fastag_home, name="fastag_home"),
    path("fastag_verify", views.fastag_verify, name="fastag_verify"),
    path("metro_home", views.metro_home, name="metro_home"),
    path("pay/credit-card/", views.credit_card_bill_payment, name="credit_card_bill_payment"),
    path("calculator/",views.fd_rd_calculator,name='calculator'),

]